import '../../core/model/expanding_item.dart';

class FaqMap {
  static final List<ExpandingItem> expandingItem = [
    ExpandingItem(
      title: 'COVID-19',
      content: {
        'What causes COVID-19 and how does it spread?':
            'COVID-19 is caused by SARS COV-2 and spreads through droplets from the nose or mouth of an infected person or by coming into contact with surfaces contaminated with the virus. The virus may either be inhaled (as droplets) or when we touch our mouth, eyes and nose while the virus is on our hands.',
        'How can I prevent myself from getting infected with COVID-19?':
            'You can protect yourself by\n·	Washing your hands frequently with soap under running water for about 40-60seconds.\n·	Using alcohol-based hand sanitizers when you cannot wash your hands.\n·	Wearing face mask to cover your nose and mouth.\n·	Avoid touching your mouth, eyes and nose (M.E.N).\n·	Keeping 2 meters distance from people around.\n·	Eat healthily (more fruits and vegetables and a lot of water) to boost your immunity. \n NOTE:  There is currently no medication to prevent you from getting this Infection.',
        'Can I get COVID-19 if I am young?':
            'Yes, you can get COVID-19 if you are young. Although older people or people with chronic diseases may be more at risk, anyone can get infected.',
        'Do I need to wear a mask if everyone around me is wearing one?':
            'Yes, you need to wear your mask even if everyone is wearing one. It protects you from   any droplet that may come from someone else as you will not inhale it. Avoid pulling your mask down when talking.',
        'Does any type of mask offer protection against COVID-19?':
            'Any mask if worn properly can at least prevent spread of droplets to and from our noses and mouths. Avoid touching the mask when you are wearing it so your hand does not pick any droplets on it.',
        'How often should I wash my mask?':
            'Most masks are disposable and should be changed after 6 hours of use. For reusable mask made from “cloth” If should be washed daily and dry in the sun. Iron it when dry and keep in a clean bag for the next use. It is better to always have spare mask to use while the other is washed.',
        'What are the symptoms of COVID-19?':
            'Persons infected with COVID-19 may have any of the following:\n·	Fever\n· Cough\n· Headache\n·	Sore throat\n·	Running nose\n·	Bodily pains\n·	Weakness\n·	Difficulty in breathing\nSome persons may not show any symptoms at all but are able to pass the infection to others while going about their routine activities.  This is a reason why it is important to always protect yourself.',
        'Can I get the disease from someone who is not showing symptoms?':
            'Yes, it is possible to get to get infected, even though the person is not showing symptoms, she/he can transmit the disease to others so we need to protect ourselves.',
        'What should I do if I have any of these symptoms?':
            'If you have any of these symptoms, quarantine  yourself and call the COVID-19 hot lines',
        'Should I wear a mask if I am visiting a friend?':
            'Yes, it is advisable to stay at home or in your dormitory if you are in school but if it becomes very necessary, wear a mask when going to visit a  friend and on return, wash your hands properly.',
        'Is it necessary to get tested for COVID-19?':
            'If you suspect you may have come in contact with someone with the disease  or have any symptoms, then it is important  to self-isolate and  call the help center for possible testing and you have not been in close contact, you do not need to do the test. Just adhere to the protocols.',
        'Should I be worried if I test positive for COVID-19 or my friend in school tests positive.':
            'If you test positive for COVID-19, you should not be worried. Be calm and stick to all instructions given you. Take your medication and eat healthily regularly. Be quick to report any changes in your condition to your nurse or doctor if you are not on admission. If your friend tests positive, you may also be tested if you have close contact with him or her. Again, stick to all instructions given to you by your healthcare provider.\nKeep your friend’s condition confidential and when they come back to school, do not stigmatise them',
        '13.	Is COVID-19 treatable and can it kill young people?':
            'COVID-19 is curable. Though some people have died from the disease including young persons, over 90% of people who get infected recover. But prevention is better than cure.'
      },
    ),
    ExpandingItem(
      title: 'MENSTRUATION',
      content: {
        'How do I reduce cramps during my period?':
            'Menstrual cramps also known as dysmenorrhoea can be minimised by applying hot water bottle covered with a towel on the abdomen. You can also take some over the counter (OTC) pain killers such as, paracetamol, Ibuprofen, etc. to reduce the pain. If there is no improvement with the use of this pain killers, see a doctor or a nurse at the clinic. Certain lifestyle modification may also help to reduce the pains. Get active and take in lot of fluids.',
        'Does having sex reduce the pain I feel during my period?':
            'Having sex at any time during your cycle including during your period does not reduce menstrual pain. Having sex during your period may predisposes you to infections.',
        'Is it normal to have a delayed period? ':
            'A difference in cycle length of a few days is not a problem. This include a delayed onset of menses (period) of a few days or a period occurring a few days earlier than expected. Some factors which may cause the period to delay include, excitement, change of environment, ill health, poor nutrition etc. However, if you have had unprotected sex and you experience delay in your period kindly visit the nearest adolescent health corner. The length of a cycle determines the date menstruation would occur.',
        'Can I use a contraceptive during my period? ':
            'Contraceptives are safe and can be used during your periods',
        'Is it true that eating too much sugar and groundnut causes menstrual pain? ':
            'Generally eating too much sugar and groundnut are not healthy for your overall health. High intake of sugar can increase cramping during your periods. Menstrual pain can also be caused by underlying medical conditions or hormonal changes.',
        'Does sugar make one bleed a lot? ':
            'The quantity of blood loss is not directly influenced by the amount of sugar intake.',
        'I bleed for 8 days, is it normal? ':
            'It normal to bleed for 8 days, normal menses range between four and half to eight (4.5- 8) days. If you always experience longer days of menstrual bleeding or it suddenly develops then you will need further assessment to rule out any underlying medical conditions.',
        'Is there a time during menstruation where I can have unprotected sex and not get pregnant?':
            'Having unprotected sex during menstruation does not lead to pregnancy in most girls. However, there is the possibility that some girls can get pregnant when they have unprotected sex during their period. Girls with short cycle length may have their fertile period while they are menstruating and may get pregnant if they have unprotected sex during this period. Also the sperms can survive for a number of days after sex therefore there is the chance of fertilizing the eggs that are released shortly after menses has ended and this can lead to pregnancy.',
        'Is it advisable to have sex during menstruation? If no what are the effects? ':
            'It is safe to have sex during your period. However, most people may find it uncomfortable. Sex during menses may predispose  you to reproductive tract infections The blood medium serves as a good environment for microorganisms to grow and multiply.',
        'How do I deal with mood swing? ':
            'Mood swings that occur during menstruation or ovulation is common. Lifestyle modification like staying physically active, getting adequate rest and sleep, staying well hydrated and taking in more fruits and vegetables. If lifestyle modification does not improve this mood swings or it gets worsen then see a nurse or doctor at the nearest clinic.',
        'What is PMS? ':
            'Pre-Menstrual Syndrome (PMS) is a group of physical and psychological signs and symptoms that occur that appear in the days preceding menses, are bothersome enough to interfere with work or lifestyle, and are followed by a symptom-free interval. It is usually because of hormonal changes during the menstrual cycle.',
        'How is sanitary pad used? ':
            'Wash hands before the sanitary pad is applied with the sticky part attached to the underwear between the vulva and the underwear. The wings of the pad are also attached to the edges of the underwear. Always wash your hands after changing your sanitary pad.',
        'How often should I change my pad in a day?':
            'It depends on how much each person bleed. Normally, the sanitary pads are changed every 3 to 4 hours if you are not menstruating much. However, it should be changed immediately you feel that it is soaked and/or uncomfortable. Always remember to wash your Hands with soap and water after changing your pad',
        'How long should my period last? ':
            'Averagely 2-7 days in early adolescents and may change to between 4.5 to 8 days in the mid reproductive age',
        'What is amenorrhoea? ':
            'Amenorrhoea refers to  the absence of menstruation'
      },
    ),
    ExpandingItem(
      title: 'CONTRACEPTION',
      content: {
        'How can I use a female condom? ':
            'The female condom is designed with two rings, an outer and inner ring.  You can squat, raise one leg, sit, or lie down in a comfortable position. Then, gently squeeze the sides of the inner(closed) rings together using your thumb and index finger so it become long and narrow. Insert the squeezed section deep as far as it can go into the vagina by placing your index finger into the condom and pushing it up while ensuring that the outer ring is hanging in the vulva. Remember to always guide the erected penis directly inside the condom. The female condom can be placed up to 8hrs before sex',
        'Can the female condom be used when the male is also using a male condom?':
            'No. The male and female condoms should not be used together during one sexual act. It is recommended that either the female uses the female condom alone or the male uses the male condom alone. The use of both in the same act of sex increase risk of friction and breakage.',
        'Can condom be reused? ':
            'No, condoms are for single use only and must be disposed immediately after each sexual act properly.',
        'Is the withdrawal method a reliable method of contraception? ':
            'No, The withdrawal method also known as coitus interruptus or “pull out” is a traditional method of contraception where the man ejaculates outside the vagina. The penis is pulls out of the vagina the moment he begins to have the sensation to ejaculate. This method of contraception is not so reliable since there are active sperm present in the pre-cum, i.e., the clear pre-ejaculate fluid released from the erected penis during stimulation. This method requires a lot of self-control and cooperation of the partner. It also does not protect against STIs.',
        'Do contraceptive methods such as pills, injectable, implants and intrauterine devices have negative effects on the health of adolescent girls? ':
            'No. All this contraceptive methods are safe and can be safely used by adolescents without any negative effects on their health. They may rather benefit from numerous non contraceptive benefit',
        'Will Emergency Contraceptives pills (ECP) destroy the womb? ':
            'No, ECP do not destroy the womb. Emergency Contraceptive Pills(ECP) should be used as soon as possible after an unprotected sex to prevent pregnancy.  ECPs are also recommended in case of sexual assault and when the other routine contraceptive methods are not used correctly. If you use ECP repeatedly, it is recommended that you visit a family planning provider for counselling so you start an appropriate method for you. Those who often take ECPs may have more side effects. ECP do not cause an abortion and so it will not work if you are already pregnant.',
        'Is it advisable to use condoms that guys provide? ':
            'If  the condom is sealed completely, not damaged and not expired it can be used.',
        'Do contraceptives destroy the womb? ':
            'No! Contraceptives are safe and does not destroy the womb. They also do not have any effect on pregnancy. However, it is appropriate to visit a trained  family planning provider for proper counselling to help you make the right choice for you before use.',
        'Does the fragrance in condoms have adverse effects in the vagina? ':
            'No. the fragrance has no effect on the vagina. Condoms are safe for most user. Few  individuals may be allergic to latex which is used to make the condoms. In such circumstances they can used condom that are latex free.',
        'I learnt that most of the contraceptive method have side effects; does the withdrawal method also have side effects? ':
            'Contraceptives have minor discomforts, however, not everyone experiences these discomforts. The withdrawal method does not pose any direct risk to the individuals but, it does not protect against Sexually Transmitted Infections (STIs) including HIV and requires a great deal of self-control to practice. Some partners may complain that it affects their sexual satisfaction.  Withdrawal method is also not a very effective method of contraception',
        'Does the use of condoms make sex less pleasurable? ':
            'Condoms are made from a thin film of latex and well lubricated therefore makes feeling as close to normal experience. Generally, it does not readily disrupt the desired pleasure of the sexual act. However, if it disturbs pleasure, ultra-thin condoms are readily available for use.',
        'What are spermicides and how are they used? ':
            'Spermicides are specially prepared gel, creams or tablets that is inserted into the vagina before a sexual act (less than 1hour). It works by killing or slowing the movement sperms that are ejaculated. To use, stay or lay in a comfortable position with one leg slightly elevated then insert the gel, tablet or cream deep into the vaginal. Remember to always check the expiry date before use. The spermicides do not protect against STIs including HIV.',
        'How can I choose a method of contraception? ':
            'Yes, you can choose a method of contraception after counselling by a trained provider, so you can make an informed decision. There are several methods available. It is appropriate to visit an adolescent corner or the nearest health facility for information, counselling and appropriate assessment so that you can make an informed decision .'
      },
    ),
    ExpandingItem(
      title: 'VAGINAL INFECTIONS/STIs',
      content: {
        'What causes vaginal infections?':
            'Vaginal infections may be caused by bacteria, yeasts, parasites. Certain practices such as douching, using soaps, perfume etc. in the vagina may irritates it. This may change the normal nature of the vaginal and may predispose you to an infection.',
        'Is it normal to get vaginal infections as a young girl?':
            'Vaginal infections can occur in women of ages (adolescents and adult females) but some measures can be taken to reduce the frequency of getting it.',
        'How do I know I have a vaginal infection?':
            'If you have any abnormal discharge of any colour, which may be foul-smelling. It may cause itching or redness of the vulva/vagina.',
        'What can I do to prevent vaginal infections?':
            'You can do the following to prevent frequent vaginal infections:\n·	Wear cotton or breathable under wears\n·	Wash and dry your panties in the sun\n·	Avoid inserting your fingers or any products into the vagina in an attempt to wash the place  \n·	Clean your perineum(anus) from front to back when you visit the toilet to avoid introducing faeces or germs into the vagina/vulva. \n·	Have your bath regularly (up to twice daily) \n·	Change your sanitary pads several times daily as needed. The sanitary pad should be changed daily either when it’s soaked or at the end of the day.\n·	Know your body well so that immediately anything changes in you, it will be identified.',
        'What should I do if I think I have vaginal infections?':
            'If you observe anything that make you think you have vaginal infection or STI, go to the adolescent health corner or see a doctor.',
        'Can vaginal infections prevent me from having children in future?':
            'Vaginal infection alone do not generally lead to inability to have childing in future. Rather complicated infection which involve the uterus and the tubes if untreated can affect your fertility i.e. ability to bear children in future.',
        'What are sexually transmitted infections (STI)?':
            'Like the name, STIs are infections mainly contracted through unprotected sex (vaginal, oral and anal) or other close sexual contacts.',
        'What are the symptoms of STIs?':
            'Many people with STIs don’t have any symptoms especially in females, so it is worth getting tested if you think you have put yourself at risk. For females, some signs and symptoms may include:\n·	a change in discharge from the vagina\n·	pain when passing urine\n·	itchiness, soreness or redness in the genital area\n·	swelling of the genitals\n·	blisters, ulcers or growth around the genital area\n·	bleeding between periods\n·	bleeding after sex\n·	pain during sex\n·	abdominal pain\n·	painful menstruation\nFor a male, some signs and symptoms may include:\n·	discharge or pus from the tip of the penis or anus;\n·	pain or a burning feeling when passing urine;\n·	itchiness, soreness or redness around the penis or under the foreskin;\n·	blisters, sores, ulcers or growth around the genital area or anus',
        'What are some common STIs?':
            'Common STIs include: Chlamydia, Gonorrhoea, Syphilis, HIV, genital warts and Genital herpes.',
        'Who is at risk of getting an STI?':
            'Anyone who has multiple sexual partners, have unprotected vaginal, anal or oral sex is at the risk of getting STIs. Never think other forms of sex can make you safe from STIs.',
        'Is it difficult to treat an STI?':
            'Most STIs can be treated especially when detected early. A proper diagnosis of the type of STI is important, this can be achieved by consulting a trained health service provider. An examination and possibly testing would be carried out. Treatment may include lotions, tablets or injections depending on the type of STI diagnosed. It is important that the course of treatment is completed. You should follow any advice given by the health service provider including avoiding sex during treatment. Note that HIV is not curable but it can be managed well with medication and a healthy lifestyle.',
        'What can I do to prevent STI?':
            'Abstinence remains the best protection against STIs. However, if you choose to be sexually active, there are ways you can help protect your sexual and reproductive health.\nKey ways include: \n·	Be faithful to your partner and limit your number of sexual partner(s) to one\n·	Use condom always to prevent pregnancy and STIs including HIV infection\n·	Avoiding overlapping sexual relationships.\n·	talking to your partner about your sexual relationships\n·	being aware of how alcohol and drugs can affect sexual decision making/n·	Getting tested for sexually transmitted infections if you think you may have put yourself at risk',
        'Which contraceptives can protect me against STIs and pregnancy? ':
            'Only condoms offer protection against STIs and pregnancy. They give dual protection, that is, protection against both pregnancy and STIs. All other methods protect against pregnancy only. The best protection against STIs is abstinence! You can also choose to abstain completely from sex until you are married.'
      },
    ),
    ExpandingItem(
      title: 'ADOLESCENT REPRODUCTIVE SYSTEM',
      content: {
        'Why are my breasts smaller than those of my friends?':
            'There may be significant variation in the size of the breast between adolescents. Some  adolescent girls may feel inferior or less attractive because of their her breast size or shape. Some feel their breast is smaller or bigger than that of her peers. The size of your breasts depend on a number of factors including genetic factors or family traits, how far you are through the process of puberty (your development). Others include the variation in the amount of fat deposited in their breasts,. If the members of your family have smaller breast, then you are more likely to inherit that trait. Breast development is one of the early signs of puberty, and usually starts to occur few years before the periods start. You will need to eat a healthy and nutritious diet, have adequate exercise and wait for your breast to develop with time as you go through puberty.',
        'Why are my breasts of different sizes? ':
            'It is normal to have your breast vary in size. Many young people and women do. If you have just started developing breasts, one breast may grow more quickly than the other. This difference in breast size may even out. However, it is also perfectly normal for breasts to be different sizes even when they\'re fully developed.',
        'Is it normal for one of my testicles to be bigger than the other?':
            'It is normal for one of your testicles to be bigger than the other. The right testicle tends to be bigger than the left. The left one usually hangs a little lower than the right within the scrotum. However, your testicles should never feel painful. You need to see the health service provider if your testicles hurt and one is far bigger than the other or feel swollen.',
        'Is it ok if my period starts so earlier than expected?':
            'A range of factors can cause a period to be early. These include:\n·	Puberty: On the average, females experience their first periods between the ages of 11 and 13 years old. The normal menstrual cycle length is between 24-38 days. me people have cycles of 21–45 days. For at least the first 6 years of having periods, a person’s periods may be irregular. If this happens once in a while, there may be no need for concern, as variations in the menstrual cycle are common.\n·	Sexually Transmitted Infections (STIs): On the other hand, certain STIs, including chlamydia, gonorrhea, and syphilis, can cause vaginal bleeding or spotting between periods. This needs prompt medical assessment and treatment. \n·	Implantation bleeding/ pregnancy: Light bleeding or spotting can occur when a fertilised egg attaches to the lining of the uterus. This usually occurs 1–2 weeks after conception and a few days earlier than an expected period.\nTalk to your health service provider for guidance.',
        'What are wet dreams?':
            'A wet dream is when a male ejaculate while he\'s sleeping. During ejaculation, semen (the fluid containing sperm) comes out of the penis and this is what you notice in your underwear. Wet dreams usually happen during dreams that have sexual images. Sometimes you may wake up from a wet dream or sleep through it.\nWet dreams begin during puberty when the body starts making more male hormone called testosterone. Some guys may feel embarrassed or even guilty about having wet dreams.  This is a normal part of growing up and you cannot stop them from happening. Other terms for wet dreams include sleep orgasm, sex dream, involuntary orgasm and nocturnal emission. It is called nocturnal emission because the ejaculation (discharge) usually occurs at night during sleep',
        'Is there something wrong with me if I don’t have wet dreams?':
            'No! There is absolutely nothing wrong with you. Usually males will start to experience wet dream when they reach puberty however some men do not experience it until later in life. Some males do not start having dreams that are sexy (erotic) in nature until their late teens while some just do not have it.',
        'How often should I have wet dreams?':
            'The frequency of nocturnal emissions can be hard to compare, as they will vary considerably from male to male. It is usually experienced by males during puberty when the body starts making more male hormone called testosterone. Wet dream occurs when you have a sexually arousing dream, and or by physical stimulation like rubbing against blankets, the bed, or a full bladder.',
        'Can I stop myself from having a wet dream?':
            'You cannot stop wet dreams, since they happen while you are asleep. If you\'re worried, try sleeping with a towel nearby to absorb the discharge. Again, if you are sleeping outside your home, have extra underwear so you can change afterwards.\nScientists believe wet dreams are caused by a rise in levels of the hormone testosterone that happens in a male\'s body during puberty. Most males have fewer wet dreams as they get older.\nIt is possible that some of your friends have had wet dreams too because it is a common experience in puberty. Note that wet dreams are harmless and not a sign of health problems. However, they can be confusing and embarrassing at first.  Talk to your health service provider about any concerns you have on your body.',
        'What Is an Erection?':
            'An erection is hardening of the penis that occurs when sponge-like tissue inside the penis fills up with blood. Usually, an erection causes the penis to enlarge and stand away from the body. Erections can go away on their own or after ejaculation, i.e. the release of semen through the urethra, the small hole at the tip of the penis.',
        'What Causes Erections?':
            'There are several causes of erections, they include:\n·	sexual arousal, such as watching a pornographic materials, erotic material/ television show or fantasizing. Others include viewing the naked body parts of the opposite sex. \n·	Erection seem to happen for no particular reason. Do not get worried when you have an erection for no obvious reason especially in the morning. It is natural and happens to people of your age.',
        'Am I Getting Too Many Erections?':
            'Some guys can experience several erections in a day, whereas others may not experience any. Each individual is different so it is not possible to say what a "normal" number of erections is/are. The hormones in the body fluctuate with age, sexual maturity, level of activity, and even the amount of sleep one gets. Unless your erections are causing you discomfort or pain, don\t worry about how many you get. You can always talk to the health service provider on questions bothering you.',
        'What Can I Do to Avoid Getting Erections?':
            'Erections usually are not controllable so you cannot do much to avoid getting them. Unless the penis is stimulated enough to ejaculate, time is the only thing that will help them go away. As your hormones settle down and you advance through puberty, the frequency of unexpected erections and wet dreams should decrease. \nYou may also have to stop watching pornographic materials, movies, pictures and all other things that causes your erection.  Always try to focus on activities that will take your mind of sexual arousal. They may include sporting, academic and religious activities.',
        'Can you get an infection from fingering or oral sex?':
            'Yes, transfer of germs from fingers or mouth to the sexual organ can caused an infection.  Fingering and oral sex can lead to infections even if you are not having penetrative sexual intercourse. Ask your boyfriend /girlfriend to wash his hands before touching your genitals. Again, if either of you has a cold sore (Herpes), don\'t have oral sex. The virus that causes cold sores can be transferred to the genitals and become genital herpes. As much as possible, abstain from sex. Use a dental dam when a girl is having oral sex or a condom when a guy is engaging oral sex to protect against infection.',
        'What is a dental dam?':
            'A dental dam is a square piece of stretchy latex or a similar material. It is placed over a person’s mouth when he/she is engaged in oral sex. Oral sex is a sexual act where someone\'s mouth touches the other person\'s genitals. External genitals are the sexual or reproductive organs that are on the outside of the body (the testicles and penis of a male, or the labia, clitoris, and vagina of a female.) A dental dam helps prevent the spread of some STIs and other infections. The use of condom by a male partner during oral sex also help to prevent the spread of STIs.',
        'Can a girl get pregnant if she has sex during her period?':
            'Yes, a girl may get pregnant if she has sex during her period. This might happen when:\n·	These girls have short menstrual cycles length, these girls usually ovulate during their menses or shortly after their menses. In this group of girls unprotected sex during or shortly after menses would have sperms deposited into the girl’s reproductive tract. These sperms can survive up to five days and lead to pregnancy. So, if a girl has unprotected sex during or on the last few day of her period, the sperm may still fertilise the egg.\n·	A girl has bleeding that she thinks is her period (even though it occurs far away from her period), but the bleeding is rather from ovulation. During ovulation is when the egg is released from the girl’s ovaries in that menstrual cycle. Few days before and after ovulation is the time when a girl is most likely to get pregnant if she has unprotected sex.  If you do have sex, use a condom every time to protect against unplanned pregnancy and STIs. For added protection, many couple use condoms along with another method of birth control. Talk to your health service provider about the best type of birth control for you.',
        'What should a girl do if she forgets her birth control pills?':
            'Birth control pills work best if taken according to schedule and at the same time each day. If you miss one or more pills, you increase your chances of releasing an egg that could be fertilised and lead to a pregnancy. You should do the following if you forget to take your pills:\n·	 Take it as soon as you remember. Take your next pill at the normal time. This may mean that you will take two pills in the same day. Continue taking your pills as prescribed.\n·	If you miss more than two pills (combined pills), you should do the following:\n·use a backup method of contraception i.e., you should either abstain from sex in the next 7 days or use a male /female condom any time you engage in sex in the next 7 days.\n·If you also had unprotected sex in the previous 5 days then u would need to use EC too.\n·Note: you are not protected against pregnancy when you restart your combined pills until you take your pills every day for 7 days in a row.\n•	If you are using the progesterone only pill and you are 3 or more hours late in taking your pill, it is considered you have missed a pill and the risk of getting pregnant from unprotected sex is very high. \nNote: you are not protected against pregnancy when you restart your progesterone pills until you take your pills every day for 2 days in a row.\nIf you are unsure what to do when you miss taking your Family Planning (FP) pill, read the pill label or please contact your FP provider immediately. Do not start FP pills without counselling and receiving instructions from your healthcare provider on how to take your missed pills'
      },
    ),
    ExpandingItem(
      title: 'SEXUAL HEALTH',
      content: {
        'Does masturbation affect my sexual health?':
            'Masturbation has been shown in some studies to have some benefits. Masturbation, can:\n·	reduce stress\n·	release tension\n·	enhance sleep quality\n·	boost concentration\n·	elevate mood\n·	relieve menstrual cramps\n·	alleviate pain\n·	improve sex. \nMasturbation has also been identified as a strategy to improve sexual health by promoting intimacy, exploring self-pleasure, desires, and needs, reducing unintended pregnancies, and preventing STIs and HIV transmission. \nIndividuals who choose to abstain from sex or who do not currently have a sexual partner may often masturbate as a sexual outlet. However, excessive masturbation can harm your relationships and everyday life. The technique used by young persons during masturbation can affect sensitivity during sex. Gripping the penis too tightly during masturbation can decrease sensitivity. Therefore, experts recommend that this technique should modified to restore sensitivity during sex. \nMasturbation can also be a source of  conflict with a person\'s religious beliefs or personal values. Masturbation does not:\n·	stunt your growth\n·	affect your ability to have children in the future\n·	damage your eyesight\n·	give you STIs\n·	cause hair to grow in your palms\n·	lead to penis shrinkage\n·	cause penis curvature\n·	lead to problems with erection',
        'What are aphrodisiacs and is it advisable to use them?':
            'Aphrodisiacs are drugs or foods that are taken to improve sexual arousal and performance. \nAdolescents may decide to take aphrodisiacs so that they can have long lasting erections, maximise sexual pleasure, intensify orgasm, increase sex drive, and stamina. It is natural for libido to fluctuate from time to time. Some factors such as stress, sleep problem, lack of exercise, use of alcohol, tobacco, marijuana and some drugs may lead to decreased libido. In addition, some adolescents may be lured into taking aphrodisiacs due to influences from their peers, curiosity, or adventure. \nIt is not advisable to take aphrodisiacs as a young person. Do not get anxious for you are still growing and things that concern your sexual health will get normal with time. Do not take any medication or substance to boost your sexual performance for they may cause harmful side effects which you cannot reverse.',
        'Is vaginal discharge normal?':
            'In most instances, vaginal discharge is perfectly normal. The amount, odour and colour can vary, depending on the time in your menstrual cycle. Normal vaginal discharge is usually clear, white, or off-white and may have a subtle smell that is not unpleasant or foul smelling. There may be more discharge when you\'re ovulating, sexually aroused or breastfeeding. This normal fluid is beneficial because it keeps the vagina clean, moist, and protects it from infection.',
        'What Are the Signs of a Problem with Vaginal Discharge?':
            'These signs can mean there\'s a problem with a girl\'s discharge:\n·	a change in smell, especially an unpleasant odour, e.g fishy smell\n·	a change in colour, especially greenish, grayish, or anything looking like pus\n·	a change in texture, such as foamy or looking like cheese\n·	vaginal itching, burning, swelling, or redness\n·	vaginal bleeding or spotting that is not a menstrual period',
        'What Can Cause Changes in Vaginal Discharge?':
            'Infections are the most common cause of unusual vaginal discharge. These infections include:\n·	yeast infections such as candidiasis  \n·	vaginal infections and vaginal vaginosis\n·	Sexually Transmitted Infections such as Gonorrhoea',
        'What Should I Do If I Notice a Change in My Vaginal Discharge?':
            'If you think your vaginal discharge has changed, make an appointment with your health care provider right away. This is especially important if you have had unprotected sex because it could be a sign of Sexually Transmitted Infections. Most causes of vaginal discharge can be treated.',
        'How can I tell if I have a yeast infection? ':
            'You will usually notices certain changes if you has a vaginal yeast infection. You may have vaginal itching and irritation; swelling and irritation of the vulva (the folds of skin outside the vagina); pain or burning sensation when you are urinating or having sex; or thick, white vaginal discharge that looks a bit like cheese. You may have one or several of these symptoms. If these happens, please see a health care provider.',
        'Can a virgin get vaginal infections?':
            'Yes, vaginal infections like bacterial vaginosis or candidiasis (yeast infection) can affect any girl including those who have never had sex. For example, yeast infections can follow the use of certain  medications or from reduce immunity. Certain diseases such as Diabetes can also make the adolescent susceptible to candidiasis. In the case of bacterial vaginosis, it is due to change in the normal balance in the vaginal. Here, there imbalance favours the overgrowth of some bacterial over the more desired ones.',
        'Why does one feel pain during sex?':
            'Several factors can cause pain during sex. These include\n·	Being tense before or during sex or being unable to become aroused.\n·	Vaginal dryness. This dryness may be caused by lack of foreplay before intercourse.\n·	Infection such as a yeast infection, urinary tract infection and Pelvic Inflammatory Disease (PID)).\n·	Injury to the vagina.\n·	Muscle spasms around the vagina. For some women, the pain of the spasms is so severe that sexual intercourse is impossible.\n·	Abnormalities of the uterus. These could include fibroid growth, if the uterus is tilted by its position. \n·	Certain conditions of the ovaries. This might include cyst on the ovaries.\n·	Past surgeries. This may leave scar tissue that can cause pain.\n·	Endometriosis. This is a condition in which the tissue similar to that which lines the uterus is found anywhere outside the uterus.',
        'What Is HPV and Why Is It a Problem?':
            'Human papillomavirus (HPV) is one of the Sexually Transmitted Infections (STIs). It is responsible for causing genital warts.\nBesides genital warts, an HPV infection can also lead to the following:\n·	In females, it has been shown to cause cervical cancer. HPV infection can also lead to cancer of the vagina, vulva, anus, mouth, and throat.\n·	In males, HPV infection may lead to cancer of the penis, anus, mouth, and throat.\nMost people infected with HPV don\'t know they have it because they don\'t notice any signs or symptoms. People may have HPV infection but not always develop genital warts, but the virus may still be in their system and could cause damage. This means that people with HPV can pass the infection to others without knowing it.\nBecause HPV can cause problems like genital warts and some kinds of cancer, a vaccine is an important step in preventing infection and protection against the spread of HPV.\nIt is recommended that all girls and boys get the vaccine from age 11 or 12 through age 26. If needed, children can get the vaccine starting at age 9 before they become sexually active.',
        'How does the HPV Vaccine Work?':
            'The HPV vaccine is recommended for people 9 to 26 years old:\nIt works best when people get all their shots on time. If you\'re under age 26 and you\'ve missed a shot, you can still catch up. Just ask the health service provider about the best way to do that. The vaccine does not protect people against strains of HPV that they might have been infected before getting the vaccine. The most effective way to prevent HPV infection is to get vaccinated before having sex for the first time. But even if you have had sex, don\'t give up on getting the vaccine. It\'s still the best way to protect against strains of the virus that you may not have come in contact with.\nThe vaccine doesn\'t protect against all types of HPV. Anyone having sex should get routine checkups. Females should get Pap smears when a service provider recommends it. The HPV vaccine is not a replacement for using condoms to protect against other strains of HPV and other STIs when having sex.',
        'What Are the Side Effects of the HPV Vaccine?':
            'Side effects that people get from the HPV vaccine usually are minor. They may include swelling or pain at the injection site, or feeling faint after getting the vaccine. As with other vaccines, there is a small chance of an allergic reaction. Most people have no trouble with the vaccine. You can make fainting less likely by sitting down for 15 minutes after each shot.',
        'How Can I Protect Myself From HPV?':
            'For people who have sex, condoms offer some protection against HPV. Condoms can\'t completely prevent infections because hard-to-see warts can be outside the area covered by a condom, and the virus can infect people even when a partner doesn\'t have warts. \nThe only way to be completely sure about preventing HPV infections and other STIs is not to have sex (abstinence). Spermicidal foams, creams, and jellies do not protect against HPV or genital warts.',
        'Can I get an infection from fingering or oral sex?':
            'Fingering and oral sex can lead to infection. Ask your partner to wash his hands before touching your genitals. And if either of you has a cold sore, don\'t have oral sex. The virus that causes cold sores can transfer to the genitals and become genital herpes. STIs can also be transmitted through oral sex.',
        'I am not ready for sex but I feel pressured, should I give in?':
            'There are variations in how each individual develops.  Some develop earlier and some later. It\'s all normal. It is important is to pay attention to your own pace of development and respect it, know what you feel ready for and what you don\'t. There is no rush. It\'s good to take your time. By taking things at a pace that is right for you, you\'ll build a stronger sense of self-respect and self-confidence. You will also be prevented from sexually transmitted infections and its complications, unwanted pregnancy and abortions.\nIt is hard to feel like the odd one out but there are others who feel like you. Find friends based on your interests, friends you can have fun with. There are young people out there who are not interested in rushing into sex.',
        'At what age can I have sex?':
            'There is no specific age to be sexually active. Having sex too early can cause both physical and emotional problems. It is recommended that adolescent wait until they are mature enough to have sex. The age for having sex varies depending on culture, socioeconomic, education and personal factors. In Ghana it is legal to have sex at age 16 years. Many adolescents may have different reasons for engaging in sex but the consequences are the same. It is important to wait until you are emotionally, physically and socially ready before you engage in sex. Do not feel pressured to have sex. Concentrate on your education and career until you are mature enough to take responsibilities or handle the consequences of being sexually active. The risks of being sexually active include:\n·	damage to the way you feel about yourself and how others feel about you\n·	getting pregnant and the complications that come with it at that age.\n·	you can get infected with sexually transmitted infections and you will have to live with it for the rest of your life. \n·	heartbreak and depression if your sexual partner is not committed to you after having sex with him or her',
        'What is the common symptom of STI?':
            ': STIs can have a range of signs and symptoms. However, some adolescents may not have any symptom, especially females. That\'s why they may go unnoticed until complications occur or a partner is diagnosed. The common symptoms of STI include:\n·	Sores or bumps on the genitals or in the oral or rectal area\n·	Painful or burning urination\n·	Discharge from the penis\n·	Unusual or odd-smelling vaginal discharge\n·	Unusual vaginal bleeding\n·	Pain during sex\n·	Sore, swollen lymph nodes, particularly in the groin but sometimes more widespread\n·	Lower abdominal pain\n·	Fever\n·	Rash over the trunk, hands or feet',
        'Is it okay to use Vaseline as a lubricant with a latex condom?':
            'No. Oil-based lubricants, like vaseline, can damage the condom and cause it to break during sex. If the condom is made of latex, then you cannot use vaseline as a lubricant because it will weaken the condom and eventually cause it to break during sexual intercourse. This may increase the risk of infection or unintended pregnancy. You should only use water-based lubricants, such as K-Y Jelly, with latex condoms.',
        'Can I get pregnant the first time I have sex?':
            'Yes, a girl can become pregnant the first time she has an unprotected sex. Anytime a girl has vaginal sex with a guy, she is at risk of becoming pregnant. If a guy ejaculates near a girl\'s vagina or pulls out after some of the semen has entered the vagina, the girl can get pregnant.\nIf you and your partner had unprotected sex (or a condom broke), see your health service provider for pregnancy and STI tests.\nIf you have ever had sex, or are thinking about having sex, talk with your health service provider about birth control options.',
        'How do I know if the man I had sex with has an STI?':
            'you will have to visit a health service provider to get tested for STIs and pregnancy. You will also need to go back to be retested for HIV (the virus that causes AIDS) again in 3 months, because it can take a while for that infection to show up in tests.\nIt is good to ask a partner about STIs, but it\'s even more important to get tested. People who have STIs often don\'t know that they\'re infected. That\'s why it\'s important to use a condom to help protect against STIs every time you have any type of sex.\nUnfortunately, alcohol and drugs take away our ability to make good decisions about things like condom use and sexual partners. When you\'re going out, always let someone know where you\'ll be, and plan a safe way to get home. Be aware of your environment, who you\'re with, and how to avoid getting into possible dangerous situations.',
        'Are there any vaccines that will protect me against STIs?':
            'Yes, there are vaccines to protect the adolescents against some sexually transmitted infections such as Hepatitis A, Hepatitis B and Human papilloma virus. Example:\n-	Hepatitis A vaccines include: Havrix and Vaqta\n-	Hepatitis B vaccines include:  Energix B, Recombivax HB, Engerix B\n-	HPV vaccines include: Gardasil, Cervarix, and Gardasil 9.\n·	Although hepatitis A is associated with contaminated food and water, it is also considered an STI. This is because it can be transmitted through oral-anal sex and from person to person.\n·	Hepatitis B is commonly passed through unprotected sex with an infected person, or by sharing toothbrushes, razors, or other items with infected blood on them. \n·	Human papillomavirus is sexually transmitted. There are several strains of the virus. The vaccine does not protect against all HPV types so they will not prevent all cases of cervical cancer.\n·	Most sexually transmitted infections do not have vaccines. The most effective ways of preventing STI are abstaining from sex, correct and consistent use of condom (using condom correctly anytime you have sex)'
      },
    ),
    ExpandingItem(
      title: 'SGBV',
      content: {
        'What is Sexual Bullying and Harassment?':
            'Sexual harassment can involve comments, gestures, actions, or attention that is intended to hurt, offend, or intimidate another person. With sexual harassment, the focus is on things like a person\'s appearance, body parts, sexual orientation, or sexual activity.\nSexual harassment may be verbal (like making comments about someone), but it doesn\'t have to be spoken. Bullies may use technology to harass someone sexually (like sending inappropriate text messages, pictures, or videos). Sometimes sexual harassment can even get physical when someone tries to kiss or touch someone who does not want to be touched.\nSexual harassment doesn\'t just happen to girls. Boys can harass girls, but girls also can harass guys, guys may harass other guys, and girls may harass other girls. Sexual harassment isn\'t limited to people of the same age, either. Adults sometimes sexually harass young people (and, occasionally, teens may harass adults, though that\'s pretty rare). \nSexual harassment and bullying are very similar they both involve unwelcome or unwanted sexual comments, attention, or physical contact. So why call one thing by two different names?\nPeople who are sexually harassed can feel threatened and scared and experience a great deal of emotional stress.\nSexual harassment or bullying may include:\n·	making sexual jokes, comments, or gestures to or about someone\n·	spreading sexual rumors (in person, by text, or online)\n·	writing sexual messages about people on bathroom stalls or in other public places\n·	showing someone inappropriate sexual pictures or videos\n·	asking someone to send you naked pictures of herself or himself \n·	posting sexual comments, pictures, or videos on social networks like Facebook, or sending explicit text messages\n·	making sexual comments or offers while pretending to be someone else online\n·	touching, grabbing, or pinching someone in a deliberately sexual way\n·	pulling at someone\'s clothing and brushing up against them in a purposefully sexual way\n·	asking someone to go out over and over again, even after the person has said no\nSending sexual messages or images by text, or "sexting," is not a good idea for many reasons. Sexting can lead to problems for you and the person getting the text, even when you are dating or in a relationship with that person. In some cases, these messages can be considered harassment or bullying and can bring very serious consequences. Also, messages or images you intend to be private can get into the wrong hands and be used to embarrass, intimidate, or humiliate. Even if you send someone\'s picture just to one other person, it can be forwarded to many other people or posted online for the world to see.\nForcing another person into doing things he or she doesn\'t want to do, such as kissing, oral sex, or intercourse, goes beyond sexual harassment or bullying. Forcing someone to do sexual things is sexual assault or rape, and it\'s a serious crime.',
        'How do you handle sexual harassment?':
            'If you think you\'re being harassed, don\'t blame yourself. People who harass or bully can be very manipulative. They are often good at blaming the other person and even at making victims blame themselves. But no one has the right to sexually harass or bully anyone else, no matter what. \nThere\'s no single right way to respond to sexual harassment. Each situation is unique. It often can be helpful to start by telling the person doing the harassing to stop. Let him or her know that this behavior is not OK with you. Sometimes that will be enough, but not always. The harasser may not stop. He or she might even laugh off your request, tease you, or bother you more.\nThat\'s why it\'s important to share what\'s happening with an adult you trust. Is there a parent, relative, coach, or teacher you can talk to? Some schools have a designated person (guidance counselor, school nurse or administrator) who\'s there to talk about bullying issues. \nIf the adult you talk to doesn\'t take your complaints seriously at first, you may have to repeat yourself or find someone else who will listen.',
        'What Makes a Healthy Relationship?':
            'A healthy relationship has the following characteristics:\n·	Mutual respect.  Respect in a relationship means that each person values and understands the other.\n·	Trust.  Having confidence in one another and feeling safe physically and emotionally in a relationship is based on trust. It is normal to get a little jealous sometimes because jealousy is a natural emotion. But how a person reacts when feeling jealous is what matters. There\'s no way you can have a healthy relationship if you don\'t trust each other.\n·	Honesty. This one goes hand-in-hand with trust because it\'s tough to trust someone when one of you isn\'t being honest. \n·	Support. It\'s not just in bad times that your partner should support you. In a healthy relationship, your significant other is there with a shoulder to cry on during difficult times and to celebrate with you when you achieve something.\n·	Fairness/equality. You need to have give-and-take in your relationship.  This means you take turns in meeting your needs. It is not only one person whose needs are met all the time. \n·	Good communication. Talk to each other and share feelings that are important to you. Do not keep feelings bottled up because you\'re afraid it\'s not what the other person wants to hear.',
        'What is an Unhealthy Relationship?':
            'A relationship is unhealthy when it involves mean, disrespectful, controlling, or abusive behavior. Some people live in homes with parents who fight a lot or abuse each other emotionally, verbally, or physically. \nMany of us learn from watching and imitating the people close to us. Young people who have lived around violent or disrespectful behavior may not have learned how to treat others with kindness and respect or how to expect the same treatment.\nIt\'s not healthy to stay in a relationship that involves abusive behavior of any kind.',
        'What are the signs of an unhealthy relationship?':
            'from seeing friends or from talking to other guys or girls\n·	wants you to quit an activity, even though you love it\n·	raises a hand when angry, like he or she is about to hit you\n·	tries to force you to go further sexually than you want to\nIf you can think of any way in which your boyfriend or girlfriend is trying to control you, makes you feel bad about yourself, isolate you from the rest of your world, or harm you physically or sexually, then it\'s time to get out. Let a trusted friend or family member know what\'s going on and make sure you\'re safe. \nIt can be tempting to make excuses or misinterpret violence, possessiveness, or anger as an expression of love. Moreover, even if you know that the person hurting you loves you, it is not healthy. No one deserves to be hit, or forced into anything they don\'t want to do.',
        'When is the best time to have sex and avoid pregnancy?':
            'The time a girl is most likely to get pregnant is about halfway between periods, when ovulation happens. Ovulation is when an egg is released from the ovaries. See the health service provider to help you calculate this.',
        'Is it okay to have sex while you have your period?':
            'It all depends on the couple and how they feel about having sex when a girl is in her period. Some females (and males) don\'t like the idea of having sex during a period. Some see it as a natural monthly break in the ‘action’. Others are perfectly comfortable with it.\nHowever, you feel, just be sure to talk it over with your partner beforehand to make sure you\'re on the same page.\nIf a girl has sex with her partner during her period, she can still get pregnant or contract an STI. So always use a condom every time you have sex.',
      },
    ),
    ExpandingItem(
      title: 'MASTURBATION',
      content: {
        'Is it normal to masturbate?':
            'From a medical standpoint, there is nothing wrong with masturbation. It\'s perfectly normal for both guys and girls to masturbate. Masturbation can release sexual tension, as well as other tensions. Masturbation cannot affect a person\'s physical health in any way.',
        'Can the health service provider tell if you have been masturbating?':
            'Usually, a healthcare professional cannot tell if a girl or guy has been masturbating. The only way it might show is if masturbation has irritated the penis or vaginal area enough that there is obvious redness.',
        'What are the potential side effects of masturbation?':
            'Masturbation is harmless. In rare cases the following may occur:\n·	Some adolescent may experience irritation or tender skin if they are too rough, but this will usually heal in a few days.\n·	Some adolescent may feel guilty about masturbation especially if it conflicts with their religious, spiritual, or cultural beliefs. However, masturbation is not immoral or wrong, and self-pleasure is not shameful.\nDiscussing feelings of guilt with a friend, health service provider might help an adolescent to move past feelings of guilt or shame that they connect with masturbation.',
        'Can masturbation affect periods?':
            ': No. Masturbation will not interfere with periods or getting pregnant.\nYou might hear all sorts of rumours about masturbation that it can cause diseases, stunt your growth, cause mental problems, lead to blindness, or stop a person from having children but those things aren\'t true.\nMasturbation is often considered a private topic and some people may feel embarrassed to talk about it. And when people are too embarrassed to talk or ask about something, they might hear and believe things that are not accurate.\nIf you have worries or questions about masturbation, talk to a health service provider or your school nurse.',
        'Will I bleed the first time I have sex?':
            'Some girls bleed the first time they have sex, but not all girls do. The reason some girls bleed the first time they have sex is because their hymen stretches or tears. The hymen is a very thin piece of skin-like tissue that partly covers the opening of the vagina. Some girls are born without much of a hymen. Other girls\' hymens cover a large portion of the vagina\'s opening. It all depends on the girl.\nWhether a girl bleeds also partly depends on whether the hymen is stretched or torn before sex. It is possible for this to happen from vigorous physical activity, tampon insertion, and masturbation or fingering.\nRemember to always use a condom every time you have sex, including the first time, to help protect against pregnancy and STIs.'
      },
    ),
  ];
}
